# Generated by Django 5.2.17 on 2026-09-01 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("expense", "Expense"),
                            ("savings", "Savings"),
                            ("returns", "Returns"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("housing", "Housing"),
                            ("utilities", "Utilities"),
                            ("transportation", "Transportation"),
                            ("groceries", "Groceries"),
                            ("healthcare", "Healthcare"),
                            ("insurance", "Insurance"),
                            ("dining_out", "Dining Out"),
                            ("entertainment", "Entertainment"),
                            ("subscriptions", "Subscriptions"),
                            ("shopping", "Shopping"),
                            ("travel", "Travel"),
                            ("personal_care", "Personal Care"),
                            ("debt_payment", "Debt Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("month_code", models.CharField(editable=False, max_length=7)),
                ("amount", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
